export const Edit = {
    database: [
        {title: 'Название объекта', field: 'name'},
        {title: 'Товарный знак', field: 'trademark'},
        {title: 'Территория', field: 'territory'},
        {title: 'Неохраноспособные элементы', field: 'nonProtectedElements'},
        {title: 'Наименование и адресс владельца', field: 'client'},
        {title: 'Номер заявки', field: 'numberOrder'},
        {title: 'Дата заявки', field: 'dateOrder'},
        {title: 'Номер регистрации', field: 'numberRegistration'},
        {title: 'Дата регистрации', field: 'dateRegistration'},
        {title: 'Дата публикации', field: 'datePublication'},
        {title: 'Дата приоритета', field: 'priorityDate1'},
        {title: 'Начало срока действия', field: 'validityStart'},
        {title: 'Конец срока действия', field: 'validityEnd'},
        {title: 'Начало срока продления', field: 'extensionStart'},
        {title: 'Конец срока продления', field: 'extensionEnd'},
        {title: 'Классы МКТУ', field: 'niceClasses'},
    ],
    affairs: [
        {title: 'Название дела', field: 'name'},
        {title: 'Вид', field: 'view'},
        {title: 'Номер', field: 'number'},
        {title: 'Статус', field: 'status'},
        {title: 'Сроки', field: 'deadline'},
        {title: 'Подписант', field: 'subscriber'},
        {title: 'Исполнитель', field: 'responsible'},
        {title: 'Вниманию', field: 'attention'},
    ],
    'mails-register': [
        {title: 'Дело', field: 'affair'},
        {title: 'Тип письма', field: 'type'},
        {title: 'Трек номер', field: 'number'},
        {title: 'Служба', field: 'services'},
        {title: 'Адресат', field: 'destination'},
        {title: 'Адрес', field: 'address'},
        {title: 'Дата', field: 'date'},
        {title: 'Описание', field: 'content'},
    ],
    contracts: [
        {title: 'Номер', field: 'number'},
        {title: 'Статус', field: 'status'},
        {title: 'Сроки', field: 'deadline'},
    ],
    documents: [
        {title: 'Номер', field: 'number'},
        {title: 'Статус', field: 'status'},
        {title: 'Языки', field: 'lang'},
        {title: 'Сроки', field: 'deadline'},
        {title: 'Заявитель', field: 'client'},
        {title: 'Доверенность', field: 'document'},
    ],
    accounts: [
        {title: 'Клиент', field: 'client'},
        {title: 'Дело', field: 'affair'},
        {title: 'Используемая валюта', field: 'type'},
        {title: 'Услуга', field: 'service'},
        {title: 'Статус', field: 'status'},
        {title: 'Оплачен', field: 'state'},
        {title: 'Дата', field: 'date'},
    ],
    client: [
        {title: 'Название', field: 'name'},
        {title: 'Адресс', field: 'address'},
        {title: 'БИН', field: 'bin'},
        {title: 'ИНН', field: 'inn'},
        {title: 'ОРГН', field: 'orgn'}
    ],
}
