export class Icons {
  static database = require('/src/assets/icons/category/database.png')
  static affairs = require('/src/assets/icons/category/books.png')
  static mailsRegistry = require('/src/assets/icons/category/mails.png')
  static mail = require('/src/assets/icons/category/email.png')
  static deadlines = require('/src/assets/icons/category/calendar.png')
  static contracts = require('/src/assets/icons/category/book.png')
  static documents = require('/src/assets/icons/category/clipboard.png')
  static accounts = require('/src/assets/icons/category/calculator.png')
  static leftArrow = require('/src/assets/icons/left-arrow.png')
  static rightArrow = require('/src/assets/icons/right-arrow.png')
  static burger = require('/src/assets/icons/burger.png')
  static grid = require('/src/assets/icons/grid.png')
  static users = require('/src/assets/icons/users.png')
}